name: Widget E2E Testing

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (using legacy-peer-deps)
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install 'serve' locally
        run: npm install serve

      - name: Serve production build
        run: npx serve dist -s -l 8080 &
        env:
          NODE_ENV: production

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8080

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true